package:
  name: terraform-1.10
  version: 1.10.5
  epoch: 4
  copyright:
    - license: BSL
  dependencies:
    provides:
      - terraform=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/terraform
      tag: v${{package.version}}
      expected-commit: 898e397ebaefb4d0c363b7332b3ba184b8852162

  - uses: go/bump
    with:
      go-version: 1.23.10
      deps: |-
        github.com/golang-jwt/jwt/v4@v4.5.2
        github.com/hashicorp/go-slug@v0.16.3
        golang.org/x/crypto@v0.37.0
        golang.org/x/net@v0.39.0
        golang.org/x/oauth2@v0.30.0
        github.com/cloudflare/circl@v1.6.1

  - uses: go/build
    with:
      go-package: go-1.23 # compatibility with GODEBUG=tlskyber=0
      packages: .
      output: terraform

test:
  pipeline:
    - name: Terraform Initialization
      runs: |
        echo "provider \"local\" {}" > example.tf
        terraform init -input=false || exit 1
        terraform --version
        terraform --help
    - name: Terraform Plan Creation
      runs: |
        terraform plan -input=false -out=tfplan || exit 1
    - name: Terraform Apply Execution
      runs: |
        terraform apply -input=false tfplan || exit 1
